/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/assets/': {
    /** Create Asset */
    post: operations['create_asset_assets__post'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AssetInsert */
    AssetInsert: {
      /**
       * Asset Name
       * @description Camel-case asset name
       */
      asset_name: string;
      /**
       * Keywords
       * @description A list of lowercase keywords that relate to this asset
       */
      keywords?: string[] | null;
      /** Image Url */
      image_url?: string | null;
    };
    /** Body_create_asset_assets__post */
    Body_create_asset_assets__post: {
      asset: components['schemas']['AssetInsert'];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Create Asset */
  create_asset_assets__post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Body_create_asset_assets__post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
